### ISSUE TITLE
Issue3

### ISSUE THREAD

**Issue by toantd1202** [toantd1202/Prometheus_new#13]
## Monitoring Network 
1. Xác định các tiêu chí giám sát network cho host.
2. Tìm hiểu các metrics tương ứng với các tiêu chí ấy ( trong phạm vị node_exporter, các em có thể tìm thêm trong một số exporter khác )
3. Viết alert rule dựa trên các tiêu chí đã định nghĩa ở 1. Cần giải thích được các operator, func PromQL sử dụng trong expr ấy.
4. Bonus: Trực quan các metric về network lên Grafana

**Comment by toantd1202** [comment]
# 1. Các tiêu chí giám sát network cho host

+ Lưu lượng luồng dữ liệu truyền, nhận hay còn gọi là băng thông. Trong đó, các luồng dữ liệu này có thể lấy theo các đơn vị, đặc tính nhau như: `packets`, `errs`, `drop`, `fifo`, `compressed`, `multicast` cho cả luồn `receive` và `transmit`. Ngoài ra `Colls` (va chạm) và `carrier` chỉ có trong luồng `transmit`.
+ Các thông tin của các interface như `ip address`, `MAC address`, `device name`, tình trạng hoạt động, loại giao diện.

# 2. Các metrics tương ứng
## Băng thông

Đối với `bandwidth`, các `metrics` ứng với tiền tố như `node_network_receive` và `node_network_transmit`. Các `metrics` này trả về kiểu dữ liệu là `counter`. `node_network_receive` trả về các giá trị ứng với luồng xuống(nhận) về host tại các mốc thời gian tương ứng, ngược lại các metrics `node_network_transmit` trả về các giá trị, thông số của luồn up(truyền), trong cùng một thời điểm, cả hai luồng đều có thể hoạt động, vì vậy, độ rộng của `bandwidth` là tổng của cả luồng lên và luồng xuống.

Các đơn vị thường dùng cho các luồng như:

+ `byte`: các dữ liệu đựơc đo bằng đơn vị là `byte`-đơn vị chuẩn, nếu muốn trả về đơn vị là `bit` thì ta thực hiện nhân giá trị trả về của `metrics` tương ứng với 8, ví dụ: `rate(node_network_transmit_bytes_total[5m]) * 8`, tốc độ truyền dữ liệu trong 5 phút được trả về với đơn vị là `bit`
+ Ngoài ra, các kiểu đơn vị khác được cung cấp như:
  + `packets`: gói data truyền/nhận
  + `errs`: lỗi xảy ra trong quá trình truyền/nhận
  + `drop`, `fifo`, `compressd`.
  + `colls`: số lượng các va chạm trên luồng truyền
  + `carrier`: số lượng sóng mang sử dụng

|Metrics|description|types|
|:-----:|:---------:|:----:|
|node_network_receive_bytes_total|Network device statistic receive_bytes|counter|
|node_network_receive_compressed_total|Network device statistic receive_compressed|counter|
|node_network_receive_drop_total|Network device statistic receive_drop|counter|
|node_network_receive_errs_total|Network device statistic receive_errs|counter|
|node_network_receive_fifo_total|Network device statistic receive_fifo|counter|
|node_network_receive_frame_total|Network device statistic receive_frame|counter|
|node_network_receive_multicast_total|Network device statistic receive_multicast|counter|
|node_network_receive_packets_total|Network device statistic receive_packets|counter|
|node_network_speed_bytes|speed_bytes value of /sys/class/net/<iface>|gauge|
|node_network_transmit_bytes_total|Network device statistic transmit_bytes|counter|
|node_network_transmit_carrier_total|Network device statistic transmit_carrier|counter|
|node_network_transmit_colls_total|Network device statistic transmit_colls|counter|
|node_network_transmit_compressed_total|Network device statistic transmit_compressed|counter|
|node_network_transmit_drop_total|Network device statistic transmit_drop|counter|
|node_network_transmit_errs_total|Network device statistic transmit_errs|counter|
|node_network_transmit_fifo_total|Network device statistic transmit_fifo|counter|
|node_network_transmit_packets_total|Network device statistic transmit_packets|counter|
|node_network_transmit_queue_length|transmit_queue_length value of /sys/class/net/<iface>|gauge|

### ví dụ 

+ `node_network_receive_bytes_total`: tổng số byte dữ liệu nhận về
+ `node_network_transmit_bytes_total`: tổng số byte dữ liệu truyền

![](https://user-images.githubusercontent.com/61723456/80829005-7e9ff900-8c10-11ea-926a-e2869e9a46b3.png)

Tổng băng thông được sử dụng: 
```
node_network_receive_bytes_total + node_network_transmit_bytes_total
```

+ `node_network_transmit_errs_total`: tổng số lỗi truyền đi
+ `node_network_transmit_packets_total`: tổng số gói truyền

![](https://user-images.githubusercontent.com/61723456/80829057-9d05f480-8c10-11ea-8f52-539b315b6980.png)

Để tính tỷ lệ lỗi truyền trong 5 phút ta có thể sử dụng:
```
  rate(node_network_transmit_errs_total[5m]) / rate(node_network_transmit_packets_total[5m])
```

Ta cũng có thể xác định đơn vị truyền cực đại thông qua `metrics`: `node_network_mtu_bytes`, metrics trả về kiểu dữ liệu là gauge.

Đối với các container, để giám sát network, ta sử dụng `cAdvisor`, một node exporter hỗ trợ việc giám sát các container.
Tương tự như `node exporter`, `cAdvisor` cũng có các metrics giám sát mạng như:

|Metrics|description|types|
|:--------:|:-------------:|:------:|
|container_network_receive_bytes_total|Cumulative count of bytes received|counter|
|container_network_receive_errors_total|Cumulative count of errors encountered while receiving|counter|
|container_network_receive_packets_dropped_total|Cumulative count of packets dropped while receiving|counter|
|container_network_receive_packets_total|Cumulative count of packets received|counter|
|container_network_transmit_bytes_total|Cumulative count of bytes transmitted|counter|
|container_network_transmit_errors_total|Cumulative count of errors encountered while transmitting|counter|
|container_network_transmit_packets_dropped_total|Cumulative count of packets dropped while transmitting|counter|
|container_network_transmit_packets_total|Cumulative count of packets transmitted|counter|

![](https://user-images.githubusercontent.com/61723456/80829118-beff7700-8c10-11ea-998b-16b5ce90c64e.png)

![](https://user-images.githubusercontent.com/61723456/80829153-cb83cf80-8c10-11ea-90aa-114d9fb4aef7.png)


## Thông tin trên các interface

Với việc sử dụng `metrics` `node_network_info`, các thông tin của interface được trả về với với các giá trị như `ip address`, `device name`, tình trạng hoạt động.

ví dụ:
```
node_network_info{address="00:00:00:00:00:00",broadcast="00:00:00:00:00:00",device="lo",duplex="",ifalias="",operstate="unknown"} 1
node_network_info{address="02:42:ac:17:00:03",broadcast="ff:ff:ff:ff:ff:ff",device="eth0",duplex="full",ifalias="",operstate="up"} 1
```
Hay với `node_network_address_assign_type` cho biết địa chỉ MAC đến từ đâu.

# 3. Viết alert rule

+ Giao diện mạng máy chủ có thể đang nhận quá nhiều dữ liệu (> 100MB/s)
```
  - alert: HostUnusualNetworkThroughputIn
    expr: sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput in (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

+ Giao diện mạng máy chủ có thể đang gửi quá nhiều dữ liệu (100 MB/s)
```
  - alert: HostUnusualNetworkThroughputOut
    expr: sum by (instance) (irate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput out (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably sending too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
+ Lỗi truyền bạn có thể sử dụng
```
  - alert: networktransmiterr
    expr:   rate(node_network_transmit_errs_total[5m]) / rate(node_network_transmit_packets_total[5m])
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "transmit error >  (instance {{ $labels.instance }})"
      description: "Host network interfaces are transmit error too much (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
